version: '3.7'
services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    labels:
      - "traefik.enable=false"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-storage:/var/lib/loki
    labels:
      - "traefik.enable=false"

volumes:
  grafana-storage:
  loki-storage:
